### ISSUE TITLE
Visit all and aid all broken

### ISSUE THREAD

**Issue by xphantomdavex** [Th3C0D3R/FoBCS#6]
//edit by TH3C0D3R: I knew I forget something ^^ but this message is not needed.

**Comment by xphantomdavex** [comment]
And clicking "Visit Tavern" and "Aid all" Separately does nothing

**Comment by Th3C0D3R** [comment]
if you click both, look at the bottom of the window, there should be a progressbar filling up. I know its not really visible and I will think of how to make it better

**Comment by Th3C0D3R** [comment]
will fix it asap

**Comment by xphantomdavex** [comment]
Oh alright yeah I did not notice that.

**Comment by Th3C0D3R** [comment]
fixed with commit c0561be7d9e281682dae380c51a90f144f7d965b
