### ISSUE TITLE
FOE-Bot (v1.1.0) not working

### ISSUE THREAD

**Issue by befire007** [Th3C0D3R/FoBCS#7]
Hello,

windows 10 Enterprise 64bits (Latest Update)
after full installation, I tried to run the Bot as administrator but nothing happening and the process FOEbots appear in task manager I tried to end task and rerun it but without success too.

**Comment by Th3C0D3R** [comment]
Please use the latest version (1.5.0.0) either use the release version from [GitHub Release](https://github.com/Th3C0D3R/FoBCS/releases/tag/v1.5-beta) or use the installer version from my website [Installer](https://th3c0d3r.xyz/fob_installer/FoB_Installer.msi)

**Comment by JiDeSnep** [comment]
Bonjour, je rencontre le même problème . Après installation le programme ne ce lance pas. J'ai installé la dernière version en date 1.6.0 mais seul la 1.5.7 se lance bien et ce connecte bien sur mon PC. 
As tu un Discord afin de mieux voir ensemble ? 
JiDe.

**Comment by Th3C0D3R** [comment]
Ok I will look into it

Discord is here:
[Discord](https://discord.gg/DJv8rNsbP7)
