### ISSUE TITLE
Me who don't know how make a pull request

### ISSUE THREAD

**Issue by Dadoudu64** [Th3C0D3R/FoBCS#8]
I have make a file for my language, the french but i don't know how create a pull request so i have open an issue and add in your code in LanguageFiles the translation in french.
[FoBCS-master.zip](https://github.com/Th3C0D3R/FoBCS/files/5684668/FoBCS-master.zip)

**Comment by Th3C0D3R** [comment]
Thank you, i will look at it

**Comment by befire007** [comment]
> Thank you, i will look at it

if you need Arabic Translation i am ready

**Comment by Th3C0D3R** [comment]
> if you need Arabic Translation i am ready

Just upload the zip here or create a pull request

**Comment by Dadoudu64** [comment]
I am French so my translation is a little different compared to google translate
